server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  db:
    database: hm-trade
  swagger:
    desc: "黑马商城交易服务管理接口文档"
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 192.168.21.132 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码