server:
  port: 8086
hm:
  db:
    database: hm-pay
  swagger:
    desc: "黑马商城支付服务管理接口文档"
    package: com.hmall.pay.controller
spring:
  rabbitmq:
    host: 192.168.21.132 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码