server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启feign对okhttp的连接池支持


hm:
  db:
    host: 192.168.21.132
    database: hm-cart
    port: 3306
  swagger:
    desc: "黑马商城购物车管理接口文档"
    package: com.hmall.cart.controller
